name: "Deploy GitHub Enterprise Server on Azure"
on:
  push:
    branches: master

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
jobs:
  terraform-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@v0.6.4
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "ghes"
      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@v0.6.4
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "ghes"
