name: "Validate terraform file"
on:
  push:
    branches-ignore: master

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@v0.6.4
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "ghes"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@v0.6.4
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "ghes"
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@v0.6.4
        with:
          tf_actions_version: "latest"
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "ghes"
